# Generated by Django 3.2.20 on 2023-11-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
