---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
      - name: Debug secrets
        run: |
          echo "DOCKERHUB_NESTECK_USER: ${{ secrets.DOCKERHUB_NESTECK_USER }}"
          echo "DOCKERHUB_NESTECK_TOKEN: ${{ secrets.DOCKERHUB_NESTECK_TOKEN }}"
      
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_NESTECK_USER }}
          password: ${{ secrets.DOCKERHUB_NESTECK_TOKEN }}
      - name: checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      # - name: Lint
      #   run: docker-compose run --rm app sh -c "flake8"
